[emacs-anzu]
src.git = "https://github.com/emacsorphanage/anzu"
src.branch = "master"
fetch.github = "emacsorphanage/anzu"

[emacs-consult]
src.git = "https://github.com/minad/consult"
src.branch = "main"
fetch.github = "minad/consult"

[emacs-consult-ghq]
src.git = "https://github.com/tomoya/consult-ghq"
src.branch = "main"
fetch.github = "tomoya/consult-ghq"

[emacs-corfu]
src.git = "https://github.com/minad/corfu"
src.branch = "main"
fetch.github = "minad/corfu"

[emacs-corfu-terminal]
src.git = "https://codeberg.org/akib/emacs-corfu-terminal"
src.branch = "master"
fetch.git = "https://codeberg.org/akib/emacs-corfu-terminal"

[emacs-devil]
src.git = "https://github.com/susam/devil"
src.branch = "main"
fetch.github = "susam/devil"

[emacs-magit]
src.git = "https://github.com/magit/magit"
src.branch = "main"
fetch.github = "magit/magit"

[emacs-modus-themes]
src.git = "https://github.com/protesilaos/modus-themes"
src.branch = "main"
fetch.github = "protesilaos/modus-themes"

[emacs-moody]
src.git = "https://github.com/tarsius/moody"
src.branch = "main"
fetch.github = "tarsius/moody"

[emacs-nerd-icons-dired]
src.git = "https://github.com/rainstormstudio/nerd-icons-dired"
src.branch = "main"
fetch.github = "rainstormstudio/nerd-icons-dired"

[emacs-nix-mode]
src.git = "https://github.com/NixOS/nix-mode"
src.branch = "master"
fetch.github = "NixOS/nix-mode"

[emacs-orderless]
src.git = "https://github.com/oantolin/orderless"
src.branch = "master"
fetch.github = "oantolin/orderless"

[emacs-projectile]
src.git = "https://github.com/bbatsov/projectile"
src.branch = "master"
fetch.github = "bbatsov/projectile"

[emacs-setup]
src.git = "https://git.sr.ht/~pkal/setup"
src.branch = "master"
fetch.git = "https://git.sr.ht/~pkal/setup"

[emacs-vertico]
src.git = "https://github.com/minad/vertico"
src.branch = "main"
fetch.git = "https://github.com/minad/vertico"