[emacs-magit]
src.git = "https://github.com/magit/magit"
src.branch = "main"
fetch.github = "magit/magit"

[emacs-nix-mode]
src.git = "https://github.com/NixOS/nix-mode"
src.branch = "master"
fetch.github = "NixOS/nix-mode"
