[emacs-consult]
src.git = "https://github.com/minad/consult"
src.branch = "main"
fetch.github = "minad/consult"

[emacs-consult-ghq]
src.git = "https://github.com/tomoya/consult-ghq"
src.branch = "main"
fetch.github = "tomoya/consult-ghq"

[emacs-magit]
src.git = "https://github.com/magit/magit"
src.branch = "main"
fetch.github = "magit/magit"

[emacs-nix-mode]
src.git = "https://github.com/NixOS/nix-mode"
src.branch = "master"
fetch.github = "NixOS/nix-mode"

[emacs-projectile]
src.git = "https://github.com/bbatsov/projectile"
src.branch = "master"
fetch.github = "bbatsov/projectile"

[emacs-setup]
src.git = "https://git.sr.ht/~pkal/setup"
src.branch = "master"
fetch.git = "https://git.sr.ht/~pkal/setup"

[emacs-vertico]
src.git = "https://github.com/minad/vertico"
src.branch = "main"
fetch.git = "https://github.com/minad/vertico"