[emacs-consult]
src.git = "https://github.com/minad/consult"
src.branch = "main"
fetch.github = "minad/consult"

[emacs-magit]
src.git = "https://github.com/magit/magit"
src.branch = "main"
fetch.github = "magit/magit"

[emacs-nix-mode]
src.git = "https://github.com/NixOS/nix-mode"
src.branch = "master"
fetch.github = "NixOS/nix-mode"

[emacs-setup]
src.git = "https://git.sr.ht/~pkal/setup"
src.branch = "master"
fetch.git = "https://git.sr.ht/~pkal/setup"

